// DIÊGOBOTELHOMUSIC — site global script v3
(() => {
  'use strict';
  const base='./'; let deferredInstallPrompt=null;
  const addCSS=()=>{if(!document.querySelector('link[data-enhancements]')){const l=document.createElement('link');l.rel='stylesheet';l.href=base+'css/enhancements.css';l.dataset.enhancements='1';document.head.appendChild(l);}};
  const registerSW=()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register(base+'service-worker.js').catch(()=>{});};
  const setTheme=t=>{const r=t==='auto'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):t;document.documentElement.dataset.theme=r;localStorage.setItem('db-theme',t);document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.textContent=t==='auto'?'Tema: Auto':t==='light'?'Tema: Claro':'Tema: Escuro');};
  const inject=()=>{if(!document.querySelector('.offline-note')){const n=document.createElement('div');n.className='offline-note';n.setAttribute('role','status');n.textContent='Modo offline — conteúdo disponível em cache';document.body.appendChild(n);}if(!document.querySelector('.pwa-install-banner')){const b=document.createElement('div');b.className='pwa-install-banner';b.setAttribute('role','dialog');b.innerHTML='<div><strong>Leve o Diêgo no seu dispositivo</strong><p>Instale o site como aplicativo no Android ou computador.</p></div><div class="pwa-install-actions"><button class="install-confirm" data-install-app type="button">Instalar</button><button data-dismiss-install type="button">Agora não</button></div>';document.body.appendChild(b);}if(!document.querySelector('[data-theme-toggle]')&&document.querySelector('.nav')){const t=document.createElement('div');t.className='utility-bar';t.innerHTML='<button class="theme-toggle" data-theme-toggle type="button">Tema</button><button class="language-toggle" data-language="en" type="button">EN</button>';document.querySelector('.nav').appendChild(t);}};
  const setup=()=>{addCSS();inject();setTheme(localStorage.getItem('db-theme')||'dark');document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.addEventListener('click',()=>{const c=localStorage.getItem('db-theme')||'dark';setTheme(c==='dark'?'light':c==='light'?'auto':'dark');}));document.querySelectorAll('[data-install-app]').forEach(b=>b.addEventListener('click',async()=>{if(!deferredInstallPrompt){alert('Abra o menu do Chrome/Edge e escolha “Instalar aplicativo” ou “Adicionar à tela inicial” se a opção não aparecer automaticamente.');return;}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;document.querySelectorAll('.pwa-install-banner').forEach(x=>x.classList.remove('show'));}));document.querySelectorAll('[data-dismiss-install]').forEach(b=>b.addEventListener('click',()=>b.closest('.pwa-install-banner')?.classList.remove('show')));document.querySelectorAll('[data-language]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('db-language',b.dataset.language);alert('Idioma inglês selecionado. A tradução completa será aplicada às páginas na próxima etapa.');}));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;document.querySelectorAll('.pwa-install-banner').forEach(x=>x.classList.add('show'));});window.addEventListener('appinstalled',()=>document.querySelectorAll('.pwa-install-banner').forEach(x=>x.classList.remove('show')));const net=()=>document.querySelector('.offline-note')?.classList.toggle('show',!navigator.onLine);addEventListener('online',net);addEventListener('offline',net);net();};
  addEventListener('load',registerSW);document.addEventListener('DOMContentLoaded',()=>{setup();const toggle=document.querySelector('.nav-toggle'),links=document.querySelector('.nav-links');if(toggle&&links){toggle.addEventListener('click',()=>{const open=links.classList.toggle('open');toggle.setAttribute('aria-expanded',open?'true':'false');});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));}document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());const chapters=document.querySelectorAll('.chapter'),container=document.getElementById('chapters');if(chapters.length&&container){const dots=document.querySelectorAll('.chapter-progress .dot'),counter=document.getElementById('chapter-current');const rev=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in-view');}),{threshold:.25});document.querySelectorAll('.chapter-reveal').forEach(e=>rev.observe(e));const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const i=[...chapters].indexOf(e.target);dots.forEach(d=>d.classList.remove('active'));dots[i]?.classList.add('active');if(counter)counter.textContent=String(i+1).padStart(2,'0');}}),{threshold:.5,root:container});chapters.forEach(c=>obs.observe(c));dots.forEach(d=>d.addEventListener('click',()=>document.getElementById(d.dataset.target)?.scrollIntoView({behavior:'smooth'})));}const lb=document.getElementById('lightbox'),im=document.getElementById('lightbox-img'),cl=document.getElementById('lightbox-close');document.querySelectorAll('.gallery-item').forEach(i=>i.addEventListener('click',()=>{if(lb&&im&&i.dataset.full){im.src=i.dataset.full;im.alt=i.querySelector('img')?.alt||'';lb.classList.add('open');}}));cl?.addEventListener('click',()=>lb.classList.remove('open'));lb?.addEventListener('click',e=>{if(e.target===lb)lb.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')lb?.classList.remove('open')});});
})();
